# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux]
        arch: [amd64, arm64]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
        id: go

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: |
          CGO_ENABLED=0 GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -trimpath -ldflags="-w -s" -o telegram-sms-${{ matrix.os }}-${{ matrix.arch }}
          chmod +x telegram-sms-${{ matrix.os }}-${{ matrix.arch }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: telegram-sms-${{ matrix.os }}-${{ matrix.arch }}
          path: telegram-sms-${{ matrix.os }}-${{ matrix.arch }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            telegram-sms-${{ matrix.os }}-${{ matrix.arch }}
